name: Cron

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Install zx
        run: npm install -g zx
      - name: Keep functions alive
        run: npx zx ./scripts/cron.mjs
